### ISSUE TITLE
New content structure meeting follow up issues

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/gibs-api-docs#3]
## RTD-dropdown
- [x] Expanded content all the way
- [x] Indent TOC levels
- [x] Code block formatting
~- [ ] Copy to clip board (nice to have)~
~- [ ] Tracking current location on page (if not too hard)~
- [x] When permalinking to an anchor that's within a nested part of the navigation panel hierarchy, auto-expand that section
- [x] Centering of table header row content
- [x] Add Admonitions
- [x] Allow for editable attributes (e.g`target="_blank"`)
## Material-UI
~- [x] Highlight the selected tab~
~- [x] Keep title text consistent~
~- [ ] Decide what we want to do with changing header text (Maybe make clickable to return to home)~
~- [x] Left Nav contrast~
~- [x] Code block coloring (if not too hard)~
~- [ ] Consider H2 bolding in content area~

**Comment by Benjaki2** [comment]
@minniewong  @mcechini The two of you can monitor progress on the `split-documentation-material` and `split-documentation-rtd` branches. The majority of the low-hanging fruit issues have been addressed.

**Comment by mcechini** [comment]
"Left Nav contrast" is subtle.  I think I would still go with a more drastic contrast.

**Comment by minniewong** [comment]
Going forward with `split-documentation-rtd` read the docs style

**Comment by minniewong** [comment]
Any possibility in researching/implementing these things?
1. Forcing external links to open in a new tab
2. Information blocks like[ these](https://learning-readthedocs.readthedocs.io/en/latest/Options/admonition.html)
3. And...still kind of miss the menu header tracking whilst scrolling the page.
